### ISSUE TITLE
Production Data Dump

### ISSUE THREAD

**Issue by dak** [Connexions/cnx-archive#197]
It would be very useful for testing purposes to get a dump of the fully transformed data from production.

**Comment by pumazi** [comment]
This isn't likely to happen. It appears we have developed around this pain point. So it's not worth the time and effort anymore.

**Comment by pumazi** [comment]
This still would be a nice thing to have. Found myself craving for it again...

**Comment by karenc** [comment]
I've written a [script](https://gist.github.com/karenc/37547fe6aed3f5df4629) for dumping and loading the database without resource files.

The script first dumps the entire database without the files and module_files table, then it gets the files and module_files rows for index.cnxml, index.cnxml.html, index_auto_generated.cnxml, then it puts all these files into a tar file for easy download.  The script can load this file into a development database.

When I tried it today on desert, the tar file is around 10G.

Example usage:

1. Download [cnxarchive_db.sh](https://gist.github.com/karenc/37547fe6aed3f5df4629)
2. Make cnxarchive_db.sh executable:
   - `chmod 755 cnxarchive_db.sh`
3. scp [cnxarchive_db.sh](https://gist.github.com/karenc/37547fe6aed3f5df4629) to desert (dev).
   - `scp cnxarchive_db.sh desert:`
4. Run cnxarchive_db.sh on desert:
   - `ssh desert`
   - `./cnxarchive_db.sh dump <db-user> <db-name>`
5. The command should end with something like `Creating "cnxarchive_dump.tar.2015-08-29"` and `Done`.
6. **Log out of desert**
7. scp the file from desert to your machine:
   - `scp desert:cnxarchive_dump.tar.2015-08-29 .`
8. Change the filename to `cnxarchive_dump.tar`:
   - `mv cnxarchive_dump.tar.2015-08-29 cnxarchive_dump.tar`
9. Load the dumped database into your development database (**will wipe the database**):
   - `./cnxarchive_db.sh load cnxarchive cnxarchive`

WIP the database doesn't work with what's on master atm.

**Comment by karenc** [comment]
@reedstrm said it would be better to include the `module_files` table but set the fileid to a dummy file in the files table.

**Comment by karenc** [comment]
One of the problems why the database doesn't work is in the dumped sql file, the users table is a foreign table:

```
--
-- Name: users; Type: FOREIGN TABLE; Schema: public; Owner: postgres; Tablespace:
--

CREATE FOREIGN TABLE users (
    id integer NOT NULL,
    username character varying(255) DEFAULT ''::character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    is_administrator boolean DEFAULT false,
    person_id integer,
    is_temp boolean DEFAULT true,
    first_name character varying(255),
    last_name character varying(255),
    full_name character varying(255),
    title character varying(255),
    uuid character varying(255)
)
SERVER oscaccounts;
```

That's outdated, see current implementation: https://github.com/Connexions/cnx-archive/blob/e4711faed30079188e99cf92103e290be1b367f7/cnxarchive/sql/schema/schema.sql#L633

**Comment by karenc** [comment]
Oops, sorry it is working.  I just dumped an outdated database.

**Comment by karenc** [comment]
Anyone wants to verify that this is working for them too?
