### ISSUE TITLE
Problem Content

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-archive#265]
This is a list of links to content that is returned in search results, but gives a 500 error when viewed.
- Stereo Depth Map Construction
  - http://cnx.org/contents/ff4baa7b-da6e-4852-ab11-404ff8811679@1.1
- EE Textbook
  - http://cnx.org/contents/c992c08b-2130-4e61-96c8-74d4c3092cc8@1.1/EE_Textbook

**Comment by reedstrm** [comment]
Hmm, I wonder how  they managed to convince the existing system to put a collection inside a collection: as Michael mentioned on the PR, this is not supposed to be possible.

**Comment by reedstrm** [comment]
That legacy links shows what happens to a collection that has the wrong status/state set, somehow. That's the collection editor interface.

**Comment by edwoodward** [comment]
It has happened before but I don't remember how. Copy and paste comes to 
mind, but I don't think that is possible unless the old collection 
editor allowed it.

**Comment by reedstrm** [comment]
This is from 2009, and Mark Horner's the author, so various forms of hackery could have been in play :-)

**Comment by edwoodward** [comment]
This appears to be fixed. Closing
