### ISSUE TITLE
Authors are not returned in alphabetical order

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-archive#275]
A user reported that the authors are not in the correct order on his content.  The content is at
 http://cnx.org/contents/484d4446-da50-4af4-bc44-d6a2e0d660df@14.1/An_Interactive_Approach_to_Sig

The author order should be: Nasser Kehtarnavaz, Philip Loizou, Mohammad Rahman 

Is currently displayed as Mohammad Rahman, Nasser Kehtarnavaz, Philip Loizou

**Comment by pumazi** [comment]
I'd suggest we put a shaded toggle in the metadata editing interface that alphabetizes the names.

**Comment by edwoodward** [comment]
Authors are displayed in the order they are published in which is correct. Closing.
