### ISSUE TITLE
Update shadow users on legacy publish

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-archive#309]

**Comment by pumazi** [comment]
I don't know that an update will be possible. The best we can do is insert the username into the users table. The other information is within plone and accounts. Both of these resources will be inaccessible by a sql table trigger. So, using a trigger to do this is probably not going to work.

**Comment by reedstrm** [comment]
For the record, (from chat) the plone users are shadowed in the 'persons' table, so we can pull from there.
