### ISSUE TITLE
User names are not updated from Legacy

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-archive#329]
Alina changed the name of one of the OSC textbook authors. The name did not update on Rewrite, but it did on Legacy. We need to add a trigger that updates users on Rewrite when a user is updated on Legacy.

**Comment by pumazi** [comment]
The user info will update on publish. However, the primary source of information is now Accounts, not Legacy. Something in legacy needs to contact accounts to update the users profile info. Though, I'm thinking that is a bit out of scope.

**Comment by edwoodward** [comment]
In this case the user info did not update on publish. The old name was 
displayed on Rewrite.

**Comment by pumazi** [comment]
@openstaxalina can you give me the url of the publication that doesn't show the authors updated name correctly. Thank you.

**Comment by openstaxalina** [comment]
Here it is: http://cnx.org/contents/8d04a686-d5e8-4798-a27d-c608e4d0e187@5.25:1/College-Physics-For-AP®-Course

**Comment by pumazi** [comment]
Was this publication made from authoring or legacy?

**Comment by openstaxalina** [comment]
legacy

**Comment by pumazi** [comment]
@edwoodward, BTW a trigger does exist. I'm guessing it is not be working as expected. 

https://github.com/Connexions/cnx-archive/blob/b4a9bc3cba9ccd356f51cd88653e558d9e617ece/cnxarchive/database.py#L522
