### ISSUE TITLE
Module PDF links are not working

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-archive#333]
When viewing the varnish logs, I noticed there were several attempts to download module PDFs from Rewrite and they returned 404. I tried the URLs and got the same 404. However, the PDFs are on Legacy and after downloading from Legacy, the PDF was still getting a 404 on Rewrite.

**Examples**
Legacy - http://legacy.cnx.org/content/m50175/1.3/?legacy=true
Rewrite - http://cnx.org/contents/61c26bc1-a1da-4c91-b16c-59cd56aafb6e/The-Pacific-Theater-and-the-At

Legacy - http://legacy.cnx.org/content/m50172/1.5/?legacy=true
Rewrite - http://cnx.org/contents/d37c8d8d-4900-432b-8a65-add5d6368d56/The-Origins-of-War:-Europe,-As

**Comment by pumazi** [comment]
The PDF links seem to be working fine for me.

**Comment by edwoodward** [comment]
Working for me as well. Closing.
