### ISSUE TITLE
Author names are not in the same order as on Legacy

### ISSUE THREAD

**Issue by amberwebb** [Connexions/cnx-archive#335]
This was reported by user in Trac ticket 13213

The order of the authors is different between legacy and rewrite. it could be a display issue or a data issue.

legacy: https://legacy.cnx.org/content/col11569/latest/

Rewrite: http://cnx.org/contents/db89c8f8-a27c-4685-ad2a-19d11a2a7e2e@21.1:1/Principles_of_Biology

**Comment by amberwebb** [comment]
Original issue: https://github.com/Connexions/webview/issues/1096

**Comment by edwoodward** [comment]
This is fixed
