### ISSUE TITLE
Search results return an indexed list of pairs, but the index is not correct.

### ISSUE THREAD

**Issue by mwharrison** [Connexions/cnx-archive#343]
When you search for a book, and it returns multiple authors, the results are sorted on an index created from the results of the search. This index is not returned in order. 

![screenshot 2015-08-27 14 13 12](https://cloud.githubusercontent.com/assets/3905516/9530489/c83cba88-4cc5-11e5-9fe9-45f3fed28b81.png)

**Comment by pumazi** [comment]
The `index` here is used by webview to point at the user information in a list in another section of this data. The order of these authors is based on their order in the database, which is defined by the order the author(s) has selected when editing the content.

Feel free to reopen this if you still think it's an issue.
