### ISSUE TITLE
In book search snippets contain raw html from within body

### ISSUE THREAD

**Issue by mwharrison** [Connexions/cnx-archive#386]
![screen shot 2015-12-07 at 11 06 34 am](https://cloud.githubusercontent.com/assets/3905516/11638351/3400b7c6-9cec-11e5-8608-5d05cddca221.png)

**Comment by mwharrison** [comment]
From @reedstrm: This is an issue with the content. The index will need to regenerated.
(putting here for documentation)

**Comment by reedstrm** [comment]
need to suppress the <cnx-pi> tags

**Comment by reedstrm** [comment]
no longer a problem:
![screenshot from 2017-06-09 17-03-10](https://user-images.githubusercontent.com/253212/26996066-c87f39e0-4d35-11e7-9808-f28397df496d.png)
