### ISSUE TITLE
hash trigger on files is too agressive

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-archive#406]
When migrating the mime-type info, updating the files table w/ mime-types a was slow. Presumption is that the hash calculating trigger is firing, chewing up time (~ 4hrs)

**Comment by reedstrm** [comment]
The related PR #403

**Comment by pumazi** [comment]
The triggers need revised to only compute when the ``file`` column is added or modified. See the trigger diffinitions at https://github.com/Connexions/cnx-archive/blob/c106067fd6671dc6d2872b9559ce4837c4774744/cnxarchive/sql/schema/triggers.sql#L175-L201

**Comment by pumazi** [comment]
Closed in #403
