### ISSUE TITLE
Invalid XML in keywords

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-archive#412]
We’ve got bad XML in the keywords for https://archive.cnx.org/contents/792137bd-4949-4250-b424-831863286a93@3.json  … `"</emphasis>horizontal line"` & `"intercept<emphasis effect="italics">"`

This is also, visible in webview (see the “Keywords” under “More Information"… https://cnx.org/contents/eSE3vUlJ@3/Introduction-to-Linear-Functio)

**Comment by pumazi** [comment]
I purpose a data migration to strip all xml from the keywords.

Furthermore. since rhaptos won’t validate the exclusion of xml from the keywords, we will put a simple trigger in to strip any xml from them on publish.

In the interim, we are working around the issue by escaping the keywords (see also https://github.com/Connexions/cnx-epub/pull/52)

**Comment by pumazi** [comment]
```
cnxarchive=# select word from keywords where word ~ '<';
                               word   
------------------------------------------------------------------
 F<sub>1</sub>
 F<sub>2</sub>
 pivot<
 <!DOCTYPE ...>
 <body>
 <em>
 <head>
 <html>
 <p>
 <strong>
 <title>
 <h1 ... h6>
 <h1>
 <li>
 <ol>
 <ul>
 <a>
 <img>
 <caption>
 <table>
 <td>
 <th>
 <tr>
 <form>
 <input>
 <label>
 <option>
 <select>
 <textarea>
 <emphasis effect="italics">x</emphasis>-
 <emphasis effect="italics">y</emphasis>-intercept
 <emphasis effect="italics">x</emphasis>-intercept
 </emphasis>horizontal line
 intercept<emphasis effect="italics">
 <emphasis
 effect="italics">repartimiento</emp
 effect="italics">Sputnik</emphasis>
 <emphasis effect="italics">Enola Gay</emphasis>
 sp<sup>2</sup> hybrid orbitals
 sp<sup>3</sup> hybrid orbitals
 sp<sup>3</sup>d hybrid orbitals
 sp<sup>3</sup>d<sup>2</sup> hybrid orbitals
 half‑life of a reaction (t<sub>1/2</sub>)
 activation energy (E<sub>a</sub>)
 </m:mrow></m:msub></m:mrow></m:math>)
 <m:mrow><m:mn>1</m:mn><m:mo>/</m:mo><m:mn>2</m:mn>
 half-life (<m:math><m:mrow><m:msub><m:mi>t</m:mi>
 </m:math>
 </m:mrow><m:mo>&#x00B0;</m:mo></m:msubsup></m:mrow>
 <m:mi>E</m:mi><m:mrow><m:mtext>cell</m:mtext>
 standard cell potential, <m:math><m:mrow><m:msubsup>
 <emphasis effect="italics">Basidiomycota</emphasis> (club fungi)
 <emphasis effect="italics">important stuff</emphasis>
(53 rows)
```

**Comment by pumazi** [comment]
It appears that the `keywords` table in production has an extra column named `re_safe_word`. I don't see it in either cnx-archive or RhaptosModuleStorage's schema definitions. I'll ignore it for now...

**Comment by reedstrm** [comment]
That's probably a remnant from some experiment back in the cowboy days of doing things directly to the production database. I've checked the rest of a schema dump from production, and there's nothing else in there that uses it (some sort of function, perhaps) so it's safe to drop.
