### ISSUE TITLE
Page files are not being sent in json

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-archive#420]
This was reported by a user.

The user reported that page files were not available on Rewrite. Looking into it, I can see that the files are listed for the module on Legacy, but they are not on Rewrite.

Rewrite URL - http://cnx.org/contents/EHRr6hjR@2.23:pDHzTeQb@13/Jb0103-Preface-to-Programming-

Legacy URL - http://legacy.cnx.org/content/m45179/1.13/content_info#cnx_downloads_header

Extras for Page - http://archive.cnx.org/extras/a431f34d-e41b-4118-8452-c16b0635cdfd%4013

**Comment by karenc** [comment]
Legacy has these downloads:
 - PDF:	`m45179_1.13.pdf`
 - XML:	`m45179_1.13.cnxml`
 - Source Export ZIP:	`m45179_1.13.zip`
 - Offline ZIP:	`m45179_1.13_offline.zip`

Rewrite only has `.pdf`.

I looked on tundra, the `.offline.zip` and `.zip` are there:

```
karen@tundra:~$ ls -l /var/www/files*/a431f*
-rw-r--r-- 2 www-data www-data 133782 Apr  4 06:57 /var/www/files2/a431f34d-e41b-4118-8452-c16b0635cdfd@13.pdf
-rw-r--r-- 2 www-data www-data 118320 Oct  7  2014 /var/www/files2/a431f34d-e41b-4118-8452-c16b0635cdfd@8.pdf
karen@tundra:~$ ls -l /var/www/files*/m45179*
...
-rw-r--r-- 1 www-data www-data  16099 Mar 27 10:38 /var/www/files2/m45179-1.13.offline.zip
-rw-r--r-- 2 www-data www-data 133782 Apr  4 06:57 /var/www/files2/m45179-1.13.pdf
-rw-r--r-- 1 www-data www-data  11738 Mar 27 10:38 /var/www/files2/m45179-1.13.zip
...
```

The reason why it's not appearing in rewrite is because for the offline zip file, we look for `m45179-1.13.complete.zip` instead of `m45179-1.13.offline.zip` or `m45179-1.13.zip`.  I'm not sure if this is a bug or not.

See https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/views.py#L119 and https://github.com/Connexions/cnx-archive/blob/master/cnxarchive/views.py#L180-L181

**Comment by kerwinso** [comment]
Export files JSON from https://archive.cnx.org/extras/a431f34d-e41b-4118-8452-c16b0635cdfd%4013:

```json
{
"isLatest": true,
"downloads": [
{
"created": "2016-04-04T06:57:15.116939-05:00",
"format": "PDF",
"filename": "jb0103-preface-to-programming-fundamentals-with-java-13.pdf",
"state": "good",
"details": "PDF file, for viewing content offline and printing.",
"path": "/exports/a431f34d-e41b-4118-8452-c16b0635cdfd%4013.pdf/jb0103-preface-to-programming-fundamentals-with-java-13.pdf",
"size": 133782
},
{
"created": null,
"format": "EPUB",
"filename": "jb0103-preface-to-programming-fundamentals-with-java-13.epub",
"state": "missing",
"details": "Electronic book format file, for viewing on mobile devices.",
"path": "/exports/a431f34d-e41b-4118-8452-c16b0635cdfd%4013.epub/jb0103-preface-to-programming-fundamentals-with-java-13.epub",
"size": 0
},
{
"created": null,
"format": "Offline ZIP",
"filename": "jb0103-preface-to-programming-fundamentals-with-java-13.zip",
"state": "missing",
"details": "An offline HTML copy of the content.  Also includes XML, included media files, and other support files.",
"path": "/exports/a431f34d-e41b-4118-8452-c16b0635cdfd%4013.zip/jb0103-preface-to-programming-fundamentals-with-java-13.zip",
"size": 0
}
],
"canPublish": [
"baldwin"
]
}
```

**Comment by kerwinso** [comment]
@edwoodward Please clarify what is the actual bug. What did you mean by 'page files were not available on Rewrite'? The term 'page files' is unfamiliar to @pumazi and me.

**Comment by edwoodward** [comment]
@kerwinso The PDF and the zip file are being displayed as available for download. However, the extras show the zip is 0 bytes and has a status of "missing". I'm not sure what is triggering the link for download since the file is 1.2MB when you download it. Regardless of the download link, extras is not correct.

Here is another example of a missing zip file in extras.  The file is available on Legacy. As Karen pointed out in her comment, it could be that the module zip file names are different than collection, so they are not being picked up in extras.

Rewrite: https://cnx.org/contents/gHr6ArMq@18/The-Circle-of-Fifths
Legacy: https://legacy.cnx.org/content/m10865/2.17/content_info#cnx_downloads_header
Extras: https://archive.cnx.org/extras/807afa02-b32a-4ccb-98cb-78e484d61ca2@18

**Comment by kerwinso** [comment]
After further research, here's my understanding of this bug:
For certain pages (maybe all of them), extras and Rewrite are showing that the ZIP file download is not available, while Legacy shows that it is.

I have suggested a fix (based on [Karen's comment above](https://github.com/Connexions/cnx-archive/issues/420#issuecomment-210201548)) with this commit: https://github.com/Connexions/cnx-archive/pull/477/commits/c430cfcd619a49cfd583a67cce6e4f429ea4356e

However, I don't know how to test it. Perhaps @edwoodward or @pumazi can help me with this.

**Comment by kerwinso** [comment]
The change for this bug was pulled out of PR #477, should be handled in a separate PR.
