### ISSUE TITLE
in-book search doesn't work on dev00

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-archive#483]
1. Go to https://dev00.cnx.org/contents/GFy_h8cu@10.61:rZudN6XP@2/Introduction (Biology)
2. Search for any keyword in the 'Search this book' field.

The left pane will open blank as if it will display search results (like it does on production). But no results ever appear.

dev00 on the left, prod on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26326743/38d5bf12-3f02-11e7-8e82-29b15725105b.png)

**Comment by edwoodward** [comment]
This has been fixed
