### ISSUE TITLE
Contextual url page extras part 1

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-archive#570]
# Description

Allow the page extras API to accept contextual urls. When a contextual url is requested, we don't need to return the list of books this page is in, which should make this API a lot faster when viewing books.

# Exit Criteria

- Page extras API accepts contextual urls
- List of "books this page is in" is not returned when a contextual url is used
- Unit tests for the above

#Acceptance / Test Plan
With the browser console open in the network tab and `extras` in the filter field, visit any book or a single page. Ignore any urls that don't have uuids in them.

Book: Out of the 2 urls with uuids that you see in the network tab, one has one uuid (the book's uuid) and the other has 2 uuids (book uuid:page uuid). If you look at the json returned by these requests, only one of them (the one that only has the book uuid) has a `books` key and it is empty.

Single page: All urls with uuids that you see in the network tab with uuids should still have only 1 uuid. If you look at the json returned by this request, there is a  `books` key in it that tells you which books that page is in.

# Story

https://trello.com/c/eEl9uQYw

** *If there's a PR, attach it to the card**

https://github.com/Connexions/cnx-archive/pull/566
https://github.com/Connexions/webview/pull/1731

Per Dante: @kerwinmoney it mostly affects stuff that loads async so maybe it won't affect the content load time. It should speed up loading the downloads tab at the bottom of the page and potentially reduce load on the DB a bit.

**Comment by kerwinso** [comment]
Verified on staging. 

Part 2 is here, will be released in a future release: https://github.com/Connexions/cnx-archive/issues/576
