### ISSUE TITLE
Contextual url page extras part 2

### ISSUE THREAD

**Issue by Dantemss** [Connexions/cnx-archive#576]
# Description

When requesting contextual page extras, return a `books` array containing only the book requested.
When requesting book extras, return an empty `books` array.

# Exit Criteria

- Contextual page extras returns a `books` array containing only the book requested.
- Book extras returns an empty `books` array.
- Unit tests for the above

# Acceptance / Test Plan

NEW acceptance criteria after chatting with Dante: 
- [ ] All `/extras/any-combination-of-uuids` urls should have a `books` key. 
- [ ] Collection `books` key is empty.
- [ ] Single page lists all books that page is in. 
- [ ] Contextual page lists only the book you asked for. 

~With the browser console open in the network tab and `extras` in the filter field, visit any book or a single page. Ignore any urls that don't have uuids in them.~

~Book: Out of the ~2~ urls with uuids that you see in the network tab, one has one uuid (the book's uuid) and the other has 2 uuids (book uuid:page uuid). If you look at the json returned by these requests, both of them have a `books` key. For the book extras, the array is empty. For the contextual page extras, it contains information about the book.~

~If you change the book uuid in the extras url to a book that does not contain the given page, or a book that does not exist, or a page that does not exist, the request should now return a 404 error.~

~Single page: All urls with uuids that you see in the network tab with uuids should still have only 1 uuid. If you look at the json returned by this request, there is a  `books` key in it that tells you which books that page is in.~

# Story

https://trello.com/c/eEl9uQYw

** *If there's a PR, attach it to the card**

https://github.com/Connexions/cnx-archive/pull/575

https://github.com/Connexions/cnx-archive/pull/577

**Comment by kerwinso** [comment]
Passing on qa.cnx.org (pointing to cnx-archive `f97fc71423b7d758873fc003e31f9c0e13f31383`).

**Comment by kerwinso** [comment]
@Dantemss Does this look right? There’s definitely >2 urls with uuid that i’m seeing in the network tab, but a couple are 302.

![image](https://user-images.githubusercontent.com/11298165/44472204-4d75c580-a5f3-11e8-97ca-d6c57f78fc9d.png)

**Comment by kerwinso** [comment]
NEW acceptance criteria after chatting with Dante: 
- [ ] All `/extras/any-combination-of-uuids` urls should have a `books` key. 
- [ ] Collection `books` key is empty.
- [ ] Single page lists all books that page is in. 
- [ ] Contextual page lists only the book you asked for.

**Comment by kerwinso** [comment]
Verified AC checklist above with https://staging.cnx.org/contents/CImQfPDv@3.11:GfaWl1GG@4/Introduction and https://staging.cnx.org/contents/HRhzJGFq@3/Visualize-Fractions.
