### ISSUE TITLE
CHANGE REQUEST: Suppress ePubs

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-archive#594]
@brittweinstein commented on [Tue Sep 25 2018](https://github.com/Connexions/cnx/issues/39)

# Description
Unfortunately, we do not currently support ePubs.  We made a change a couple years ago to suppress ePubs on CNX.  However, customer support noted that some of the books have ePubs available again.  

We need to remove the "EPUB" option entirely.  

The comment below lists all the places from which they should be removed.

# Impact
* **Severity**: [ ] High [x] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [x] Medium  [ ] Low

# Acceptance
No OpenStax books have ePubs available on cnx.org
There is a mechanism in place so that new OpenStax books will not get ePubs.

**Comment by openstaxalina** [comment]
**On cnx.org:**
![suppressepubs1](https://user-images.githubusercontent.com/7863733/48281801-5a010180-e41d-11e8-8107-ea59baa5d86d.png)

**In legacy:**
...none?

**Comment by omehes** [comment]
Verified on staging.cnx.org
No epub is visible anywhere in webview in any book and any expected location

Legacy still has it!

{"date": "2018-12-10 18:03:25 CST",
 "webview": "9afc493b8f9c2fee608555a680fccda15d57d569 (v0.43.0)",
 "cnx-archive": "4.7.0",
 "cnx-publishing": "0.14.1",
 "oer.exports": "xiao.xiao v0.68.0",
 "press": "7.2.0",
 "cnx-deploy": "v2.33.1"
}
